//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.13 at 09:30:34 AM PST 
//


package uk.org.siri;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for Error: Service does not support requested capability.
 * 
 * <p>Java class for CapabilityNotSupportedErrorStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CapabilityNotSupportedErrorStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CapabilityRef" type="{http://www.siri.org.uk/}CapabilityRefStructure"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CapabilityNotSupportedErrorStructure", propOrder = {
    "capabilityRef"
})
public class CapabilityNotSupportedErrorStructure {

    @XmlElement(name = "CapabilityRef", required = true)
    protected CapabilityRefStructure capabilityRef;

    /**
     * Gets the value of the capabilityRef property.
     * 
     * @return
     *     possible object is
     *     {@link CapabilityRefStructure }
     *     
     */
    public CapabilityRefStructure getCapabilityRef() {
        return capabilityRef;
    }

    /**
     * Sets the value of the capabilityRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapabilityRefStructure }
     *     
     */
    public void setCapabilityRef(CapabilityRefStructure value) {
        this.capabilityRef = value;
    }

}
