//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.13 at 09:30:34 AM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.siri.org.uk/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package uk.org.siri;
