//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.13 at 09:30:34 AM PST 
//


package uk.org.siri;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Subscription Request for Stop Timetables
 * 
 * <p>Java class for StopTimetableSubscriptionStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StopTimetableSubscriptionStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.siri.org.uk/}AbstractSubscriptionStructure">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.siri.org.uk/}StopTimetableRequest"/>
 *         &lt;any minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StopTimetableSubscriptionStructure", propOrder = {
    "stopTimetableRequest",
    "any"
})
public class StopTimetableSubscriptionStructure
    extends AbstractSubscriptionStructure
{

    @XmlElement(name = "StopTimetableRequest", required = true)
    protected StopTimetableRequestStructure stopTimetableRequest;
    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the stopTimetableRequest property.
     * 
     * @return
     *     possible object is
     *     {@link StopTimetableRequestStructure }
     *     
     */
    public StopTimetableRequestStructure getStopTimetableRequest() {
        return stopTimetableRequest;
    }

    /**
     * Sets the value of the stopTimetableRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link StopTimetableRequestStructure }
     *     
     */
    public void setStopTimetableRequest(StopTimetableRequestStructure value) {
        this.stopTimetableRequest = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }

}
