//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.13 at 09:30:34 AM PST 
//


package uk.org.siri;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for SIRI Subscription Request 
 * 
 * <p>Java class for SubscriptionRequestStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubscriptionRequestStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.siri.org.uk/}AbstractSubscriptionRequestStructure">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.siri.org.uk/}SiriSubscriptionRequestGroup"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubscriptionRequestStructure", propOrder = {
    "productionTimetableSubscriptionRequest",
    "estimatedTimetableSubscriptionRequest",
    "stopTimetableSubscriptionRequest",
    "stopMonitoringSubscriptionRequest",
    "vehicleMonitoringSubscriptionRequest",
    "connectionTimetableSubscriptionRequest",
    "connectionMonitoringSubscriptionRequest",
    "generalMessageSubscriptionRequest"
})
@XmlSeeAlso({
    SubscriptionRequest.class
})
public class SubscriptionRequestStructure
    extends AbstractSubscriptionRequestStructure
{

    @XmlElement(name = "ProductionTimetableSubscriptionRequest")
    protected List<ProductionTimetableSubscriptionRequest> productionTimetableSubscriptionRequest;
    @XmlElement(name = "EstimatedTimetableSubscriptionRequest")
    protected List<EstimatedTimetableSubscriptionStructure> estimatedTimetableSubscriptionRequest;
    @XmlElement(name = "StopTimetableSubscriptionRequest")
    protected StopTimetableSubscriptionStructure stopTimetableSubscriptionRequest;
    @XmlElement(name = "StopMonitoringSubscriptionRequest")
    protected List<StopMonitoringSubscriptionStructure> stopMonitoringSubscriptionRequest;
    @XmlElement(name = "VehicleMonitoringSubscriptionRequest")
    protected List<VehicleMonitoringSubscriptionStructure> vehicleMonitoringSubscriptionRequest;
    @XmlElement(name = "ConnectionTimetableSubscriptionRequest")
    protected ConnectionTimetableSubscriptionStructure connectionTimetableSubscriptionRequest;
    @XmlElement(name = "ConnectionMonitoringSubscriptionRequest")
    protected List<ConnectionMonitoringSubscriptionRequestStructure> connectionMonitoringSubscriptionRequest;
    @XmlElement(name = "GeneralMessageSubscriptionRequest")
    protected List<GeneralMessageSubscriptionStructure> generalMessageSubscriptionRequest;

    /**
     * Gets the value of the productionTimetableSubscriptionRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productionTimetableSubscriptionRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductionTimetableSubscriptionRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductionTimetableSubscriptionRequest }
     * 
     * 
     */
    public List<ProductionTimetableSubscriptionRequest> getProductionTimetableSubscriptionRequest() {
        if (productionTimetableSubscriptionRequest == null) {
            productionTimetableSubscriptionRequest = new ArrayList<ProductionTimetableSubscriptionRequest>();
        }
        return this.productionTimetableSubscriptionRequest;
    }

    /**
     * Gets the value of the estimatedTimetableSubscriptionRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the estimatedTimetableSubscriptionRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEstimatedTimetableSubscriptionRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EstimatedTimetableSubscriptionStructure }
     * 
     * 
     */
    public List<EstimatedTimetableSubscriptionStructure> getEstimatedTimetableSubscriptionRequest() {
        if (estimatedTimetableSubscriptionRequest == null) {
            estimatedTimetableSubscriptionRequest = new ArrayList<EstimatedTimetableSubscriptionStructure>();
        }
        return this.estimatedTimetableSubscriptionRequest;
    }

    /**
     * Gets the value of the stopTimetableSubscriptionRequest property.
     * 
     * @return
     *     possible object is
     *     {@link StopTimetableSubscriptionStructure }
     *     
     */
    public StopTimetableSubscriptionStructure getStopTimetableSubscriptionRequest() {
        return stopTimetableSubscriptionRequest;
    }

    /**
     * Sets the value of the stopTimetableSubscriptionRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link StopTimetableSubscriptionStructure }
     *     
     */
    public void setStopTimetableSubscriptionRequest(StopTimetableSubscriptionStructure value) {
        this.stopTimetableSubscriptionRequest = value;
    }

    /**
     * Gets the value of the stopMonitoringSubscriptionRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stopMonitoringSubscriptionRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStopMonitoringSubscriptionRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StopMonitoringSubscriptionStructure }
     * 
     * 
     */
    public List<StopMonitoringSubscriptionStructure> getStopMonitoringSubscriptionRequest() {
        if (stopMonitoringSubscriptionRequest == null) {
            stopMonitoringSubscriptionRequest = new ArrayList<StopMonitoringSubscriptionStructure>();
        }
        return this.stopMonitoringSubscriptionRequest;
    }

    /**
     * Gets the value of the vehicleMonitoringSubscriptionRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vehicleMonitoringSubscriptionRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVehicleMonitoringSubscriptionRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VehicleMonitoringSubscriptionStructure }
     * 
     * 
     */
    public List<VehicleMonitoringSubscriptionStructure> getVehicleMonitoringSubscriptionRequest() {
        if (vehicleMonitoringSubscriptionRequest == null) {
            vehicleMonitoringSubscriptionRequest = new ArrayList<VehicleMonitoringSubscriptionStructure>();
        }
        return this.vehicleMonitoringSubscriptionRequest;
    }

    /**
     * Gets the value of the connectionTimetableSubscriptionRequest property.
     * 
     * @return
     *     possible object is
     *     {@link ConnectionTimetableSubscriptionStructure }
     *     
     */
    public ConnectionTimetableSubscriptionStructure getConnectionTimetableSubscriptionRequest() {
        return connectionTimetableSubscriptionRequest;
    }

    /**
     * Sets the value of the connectionTimetableSubscriptionRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConnectionTimetableSubscriptionStructure }
     *     
     */
    public void setConnectionTimetableSubscriptionRequest(ConnectionTimetableSubscriptionStructure value) {
        this.connectionTimetableSubscriptionRequest = value;
    }

    /**
     * Gets the value of the connectionMonitoringSubscriptionRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the connectionMonitoringSubscriptionRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConnectionMonitoringSubscriptionRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConnectionMonitoringSubscriptionRequestStructure }
     * 
     * 
     */
    public List<ConnectionMonitoringSubscriptionRequestStructure> getConnectionMonitoringSubscriptionRequest() {
        if (connectionMonitoringSubscriptionRequest == null) {
            connectionMonitoringSubscriptionRequest = new ArrayList<ConnectionMonitoringSubscriptionRequestStructure>();
        }
        return this.connectionMonitoringSubscriptionRequest;
    }

    /**
     * Gets the value of the generalMessageSubscriptionRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the generalMessageSubscriptionRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGeneralMessageSubscriptionRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GeneralMessageSubscriptionStructure }
     * 
     * 
     */
    public List<GeneralMessageSubscriptionStructure> getGeneralMessageSubscriptionRequest() {
        if (generalMessageSubscriptionRequest == null) {
            generalMessageSubscriptionRequest = new ArrayList<GeneralMessageSubscriptionStructure>();
        }
        return this.generalMessageSubscriptionRequest;
    }

}
