//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.13 at 09:30:34 AM PST 
//


package uk.org.siri;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;
import java.util.Date;


/**
 * Data type for Timetabled Visit of a vehicle to a stop. May provide information about the arrival, the departure or both.
 * 
 * <p>Java class for TimetabledStopVisitStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TimetabledStopVisitStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.siri.org.uk/}AbstractIdentifiedItemStructure">
 *       &lt;sequence>
 *         &lt;element name="MonitoringRef" type="{http://www.siri.org.uk/}MonitoringRefStructure"/>
 *         &lt;choice>
 *           &lt;element name="TargetedVehicleJourney" type="{http://www.siri.org.uk/}TargetedVehicleJourneyStructure"/>
 *           &lt;group ref="{http://www.siri.org.uk/}TargetedVehicleJourneyAsFlatGroup"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.siri.org.uk/}Extensions" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimetabledStopVisitStructure", propOrder = {
    "rest"
})
public class TimetabledStopVisitStructure
    extends AbstractIdentifiedItemStructure
{

    @XmlElementRefs({
        @XmlElementRef(name = "JourneyNote", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "DirectionName", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "DeparturePlatformName", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "DestinationAimedArrivalTime", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "ArrivalPlatformName", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "OperatorRef", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "ArrivalBoardingActivity", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "HeadwayService", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "ServiceFeatureRef", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "Via", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "OriginName", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "ProductCategoryRef", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "AimedArrivalTime", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "VehicleMode", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "DepartureBoardingActivity", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "BlockRef", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "MonitoringRef", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "DirectionRef", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "OriginShortName", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "VehicleJourneyName", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "AimedDepartureTime", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "OriginAimedDepartureTime", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "DestinationRef", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "FramedVehicleJourneyRef", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "CourseOfJourneyRef", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "TargetedVehicleJourney", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "LineRef", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "RouteRef", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "DestinationShortName", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "StopPointRef", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "Order", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "TimingPoint", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "ExternalLineRef", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "DestinationName", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "JourneyPatternRef", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "AimedHeadwayInterval", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "OriginRef", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "VisitNumber", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "PublishedLineName", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "VehicleFeatureRef", namespace = "http://www.siri.org.uk/", type = JAXBElement.class),
        @XmlElementRef(name = "Extensions", namespace = "http://www.siri.org.uk/", type = JAXBElement.class)
    })
    protected List<JAXBElement<?>> rest;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "OperatorRef" is used by two different parts of a schema. See: 
     * line 508 of file:/Users/bdferris/Desktop/Downloads/siri-1.0/ref/siri_reference-v1.0.xsd
     * line 508 of file:/Users/bdferris/Desktop/Downloads/siri-1.0/ref/siri_reference-v1.0.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the rest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link NaturalLanguageStringStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link NaturalLanguageStringStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link NaturalLanguageStringStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link Date }{@code >}
     * {@link JAXBElement }{@code <}{@link NaturalLanguageStringStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link OperatorRefStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link ArrivalBoardingActivityEnumeration }{@code >}
     * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * {@link JAXBElement }{@code <}{@link ServiceFeatureRefStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link PlaceNameStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link ProductCategoryRefStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link NaturalLanguagePlaceNameStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link VehicleModesEnumeration }{@code >}
     * {@link JAXBElement }{@code <}{@link Date }{@code >}
     * {@link JAXBElement }{@code <}{@link DepartureBoardingActivityEnumeration }{@code >}
     * {@link JAXBElement }{@code <}{@link MonitoringRefStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link BlockRefStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link NaturalLanguagePlaceNameStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link DirectionRefStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link NaturalLanguageStringStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link Date }{@code >}
     * {@link JAXBElement }{@code <}{@link Date }{@code >}
     * {@link JAXBElement }{@code <}{@link DestinationRefStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link FramedVehicleJourneyRefStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link TargetedVehicleJourneyStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link CourseOfJourneyStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link RouteRefStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link LineRefStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link NaturalLanguagePlaceNameStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link StopPointRefStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * {@link JAXBElement }{@code <}{@link LineRefStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link NaturalLanguageStringStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link JourneyPatternRefStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link Duration }{@code >}
     * {@link JAXBElement }{@code <}{@link JourneyPlaceRefStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link NaturalLanguageStringStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link VehicleFeatureRefStructure }{@code >}
     * {@link JAXBElement }{@code <}{@link ExtensionsStructure }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getRest() {
        if (rest == null) {
            rest = new ArrayList<JAXBElement<?>>();
        }
        return this.rest;
    }

}
