//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 10:01:21 AM PDT 
//


package org.onebusaway.siri;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for our custom OneBusAwayAffects structure.
 * 
 * <p>Java class for OneBusAwayAffectsStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OneBusAwayAffectsStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Applications" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AffectedApplication" type="{http://onebusaway.org/siri}AffectedApplicationStructure" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OneBusAwayAffectsStructure", propOrder = {
    "applications"
})
@XmlSeeAlso({
    OneBusAwayAffects.class
})
public class OneBusAwayAffectsStructure {

    @XmlElement(name = "Applications")
    protected OneBusAwayAffectsStructure.Applications applications;

    /**
     * Gets the value of the applications property.
     * 
     * @return
     *     possible object is
     *     {@link OneBusAwayAffectsStructure.Applications }
     *     
     */
    public OneBusAwayAffectsStructure.Applications getApplications() {
        return applications;
    }

    /**
     * Sets the value of the applications property.
     * 
     * @param value
     *     allowed object is
     *     {@link OneBusAwayAffectsStructure.Applications }
     *     
     */
    public void setApplications(OneBusAwayAffectsStructure.Applications value) {
        this.applications = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AffectedApplication" type="{http://onebusaway.org/siri}AffectedApplicationStructure" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "affectedApplication"
    })
    public static class Applications {

        @XmlElement(name = "AffectedApplication", required = true)
        protected List<AffectedApplicationStructure> affectedApplication;

        /**
         * Gets the value of the affectedApplication property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the affectedApplication property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAffectedApplication().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AffectedApplicationStructure }
         * 
         * 
         */
        public List<AffectedApplicationStructure> getAffectedApplication() {
            if (affectedApplication == null) {
                affectedApplication = new ArrayList<AffectedApplicationStructure>();
            }
            return this.affectedApplication;
        }

    }

}
