//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 10:01:21 AM PDT 
//


package org.onebusaway.siri;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Custom structure capturing our extensions to the SIRI SX Consequence element.
 *       
 * 
 * <p>Java class for OneBusAwayConsequenceStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OneBusAwayConsequenceStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DiversionPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OneBusAwayConsequenceStructure", propOrder = {
    "diversionPath"
})
@XmlSeeAlso({
    OneBusAwayConsequence.class
})
public class OneBusAwayConsequenceStructure {

    @XmlElement(name = "DiversionPath")
    protected String diversionPath;

    /**
     * Gets the value of the diversionPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiversionPath() {
        return diversionPath;
    }

    /**
     * Sets the value of the diversionPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiversionPath(String value) {
        this.diversionPath = value;
    }

}
